### ISSUE TITLE
GakujoGUIのアップデートについて

### ISSUE THREAD

**Issue by nharu-0630** [arkwnet/shizudai-tech#1]
GakujoGUIをWPFにアップデートしたため，リポジトリのURLが変わりました．
旧 : [https://github.com/xyzyxJP/GakujoGUI](https://github.com/xyzyxJP/GakujoGUI)
新 : [https://github.com/xyzyxJP/GakujoGUI-WPF](https://github.com/xyzyxJP/GakujoGUI-WPF)

公式サイトのURLについては変わりません．

修正と動作確認をお願いいたします．

**Comment by arkwnet** [comment]
93f89a6 で修正しました。
